config/routes.rb
Rails.application.routes.draw do
  resources :lavanderia
  resources :quartos
  resources :banheiros
  resources :cozinhas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/quarto.rb
class Quarto < ApplicationRecord
end

app/controllers/quartos_controller.rb
class QuartosController < ApplicationController
  before_action :set_quarto, only: %i[ show edit update destroy ]

  # GET /quartos or /quartos.json
  def index
    @quartos = Quarto.all
  end

  # GET /quartos/1 or /quartos/1.json
  def show
  end

  # GET /quartos/new
  def new
    @quarto = Quarto.new
  end

  # GET /quartos/1/edit
  def edit
  end

  # POST /quartos or /quartos.json
  def create
    @quarto = Quarto.new(quarto_params)

    respond_to do |format|
      if @quarto.save
        format.html { render :show, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @quarto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quarto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quartos/1 or /quartos/1.json
  # def update
  #   respond_to do |format|
  #     if @quarto.update(quarto_params)
  #       format.html { redirect_to quarto_url(@quarto), notice: "Quarto was successfully updated." }
  #       format.json { render :show, status: :ok, location: @quarto }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @quarto.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /quartos/1 or /quartos/1.json
  def destroy
    @quarto.destroy

    respond_to do |format|
      format.html { render :show, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quarto
      @quarto = Quarto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quarto_params
      params.require(:quarto).permit(:item, :comprado)
    end
end

app/helpers/quartos_helper.rb
module QuartosHelper
end

app/views/quartos/_form.html.erb
<%= form_with(model: quarto) do |form| %>
  <% if quarto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quarto.errors.count, "error") %> prohibited this quarto from being saved:</h2>

      <ul>
        <% quarto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.text_field :item %>
  </div>

  <div>
    <%= form.label :comprado, style: "display: block" %>
    <%= form.check_box :comprado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quartos/_quarto.html.erb
<div id="<%= dom_id quarto %>">
  <p>
    <strong>Item:</strong>
    <%= quarto.item %>
  </p>

  <p>
    <strong>Comprado:</strong>
    <%= quarto.comprado %>
  </p>

</div>

app/views/quartos/edit.html.erb
# <h1>Editing quarto</h1>

# <%= render "form", quarto: @quarto %>

# <br>

# <div>
#   <%= link_to "Show this quarto", @quarto %> |
#   <%= link_to "Back to quartos", quartos_path %>
# </div>

app/views/quartos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Quarto</h1>


<div id="quartos">
  <% @quartos.each do |quarto| %>
    <%= render quarto %>

  <% end %>
</div>

<%= link_to "Novo item", new_quarto_path %>

app/views/quartos/new.html.erb
<h1>New quarto</h1>

<%= render "form", quarto: @quarto %>

<br>

<div>
  <button type="button" onclick="window.location.href='<%= root_path %>'">
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAxklEQVRIS2NkoDFgpLH5DHS3wAHoo/lArECmzx4A9SUC8QGYfnQfgBTIk2k4TNsHIEMQlwX/oRLkBh2GfnSDhr8FC4BBmIAnjggGEaH4BRlwAYgdgRgUmeiAKhaADAUZDrIEZBkyIGgBTAEhn8DkQWkeFGwwMPAWEHI5zIUfgQodyAkiYiy4CDWcrEgmlNFA4Z2AxxVEx8FoUQEPAVoU1w+BcaQAiyd0C0BJDxSR5NYJIMNBieAALgsIJVOS5clNLURbRHMLAJ8WMhnOi1xiAAAAAElFTkSuQmCC"/>
  </button>
</div>

app/views/quartos/show.html.erb
# <p style="color: green"><%= notice %></p>

# <%= render @quarto %>

# <div>
#   <%= link_to "Edit this quarto", edit_quarto_path(@quarto) %> |
#   <%= link_to "Back to quartos", quartos_path %>

#   <%= button_to "Destroy this quarto", @quarto, method: :delete %>
# </div>