config/routes.rb
Rails.application.routes.draw do
  resources :lavanderia
  resources :quartos
  resources :banheiros
  resources :cozinhas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/cozinha.rb
class Cozinha < ApplicationRecord
end

app/controllers/cozinhas_controller.rb
class CozinhasController < ApplicationController
  before_action :set_cozinha, only: %i[ show edit update destroy ]

  # GET /cozinhas or /cozinhas.json
  def index
    @cozinhas = Cozinha.all
  end

  # GET /cozinhas/1 or /cozinhas/1.json
  def show
  end

  # GET /cozinhas/new
  def new
    @cozinha = Cozinha.new
  end

  # GET /cozinhas/1/edit
  # def edit
  # end

  # POST /cozinhas or /cozinhas.json
  def create
    @cozinha = Cozinha.new(cozinha_params)

    respond_to do |format|
      if @cozinha.save
        format.html { render :show, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @cozinha }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cozinha.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cozinhas/1 or /cozinhas/1.json
  # def update
  #   respond_to do |format|
  #     if @cozinha.update(cozinha_params)
  #       format.html { redirect_to cozinha_url(@cozinha), notice: "Cozinha was successfully updated." }
  #       format.json { render :show, status: :ok, location: @cozinha }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @cozinha.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /cozinhas/1 or /cozinhas/1.json
  def destroy
    @cozinha.destroy

    respond_to do |format|
      format.html { render :show, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cozinha
      @cozinha = Cozinha.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cozinha_params
      params.require(:cozinha).permit(:item, :comprado)
    end
end

app/helpers/cozinhas_helper.rb
module CozinhasHelper
end

app/views/cozinhas/_cozinha.html.erb
<div id="<%= dom_id cozinha %>">
  <p>
    <strong>Item:</strong>
    <%= cozinha.item %>
  </p>

  <p>
    <strong>Comprado:</strong>
    <%= cozinha.comprado %>
  </p>

</div>

app/views/cozinhas/_form.html.erb
<%= form_with(model: cozinha) do |form| %>
  <% if cozinha.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cozinha.errors.count, "error") %> prohibited this cozinha from being saved:</h2>

      <ul>
        <% cozinha.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.text_field :item %>
  </div>

  <div>
    <%= form.label :comprado, style: "display: block" %>
    <%= form.check_box :comprado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cozinhas/edit.html.erb
# <h1>Editing cozinha</h1>

# <%= render "form", cozinha: @cozinha %>

# <br>

# <div>
#   <%= link_to "Ver este item", @cozinha %> |
#   <%= link_to "Voltar para itens da cozinha", cozinhas_path %>
# </div>

app/views/cozinhas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cozinha</h1>

<div id="cozinhas">
  <% @cozinhas.each do |cozinha| %>
    <%= render cozinha %>

  <% end %>
</div>

<%= link_to "Novo item", new_cozinha_path %>

app/views/cozinhas/new.html.erb
<h1>New cozinha</h1>

<%= render "form", cozinha: @cozinha %>

<br>

<div>
  <button type="button" onclick="window.location.href='<%= root_path %>'">
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAxklEQVRIS2NkoDFgpLH5DHS3wAHoo/lArECmzx4A9SUC8QGYfnQfgBTIk2k4TNsHIEMQlwX/oRLkBh2GfnSDhr8FC4BBmIAnjggGEaH4BRlwAYgdgRgUmeiAKhaADAUZDrIEZBkyIGgBTAEhn8DkQWkeFGwwMPAWEHI5zIUfgQodyAkiYiy4CDWcrEgmlNFA4Z2AxxVEx8FoUQEPAVoU1w+BcaQAiyd0C0BJDxSR5NYJIMNBieAALgsIJVOS5clNLURbRHMLAJ8WMhnOi1xiAAAAAElFTkSuQmCC"/>
  </button>
</div>

app/views/cozinhas/show.html.erb
# <p style="color: green"><%= notice %></p>

# <%= render @cozinha %>

# <div>
#   <%= link_to "Edit this cozinha", edit_cozinha_path(@cozinha) %> |
#   <%= link_to "Voltar para itens da cozinha", cozinhas_path %>

#   <%= button_to "Destroy this cozinha", @cozinha, method: :delete %>
# </div>