config/routes.rb
Rails.application.routes.draw do
  resources :lavanderia
  resources :quartos
  resources :banheiros
  resources :cozinhas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/banheiro.rb
class Banheiro < ApplicationRecord
end

app/controllers/banheiros_controller.rb
class BanheirosController < ApplicationController
  before_action :set_banheiro, only: %i[ show edit update destroy ]

  # GET /banheiros or /banheiros.json
  def index
    @banheiros = Banheiro.all
  end

  # GET /banheiros/1 or /banheiros/1.json
  def show
  end

  # GET /banheiros/new
  def new
    @banheiro = Banheiro.new
  end

  # GET /banheiros/1/edit
  # def edit
  # end

  # POST /banheiros or /banheiros.json
  def create
    @banheiro = Banheiro.new(banheiro_params)

    respond_to do |format|
      if @banheiro.save
        format.html { render :show, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @banheiro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @banheiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /banheiros/1 or /banheiros/1.json
  # def update
  #   respond_to do |format|
  #     if @banheiro.update(banheiro_params)
  #       format.html { redirect_to banheiro_url(@banheiro), notice: "Item was successfully updated." }
  #       format.json { render :show, status: :ok, location: @banheiro }
  #     else
  #       format.html { render :edit, status: :unprocessable_entity }
  #       format.json { render json: @banheiro.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /banheiros/1 or /banheiros/1.json
  def destroy
    @banheiro.destroy

    respond_to do |format|
      format.html { render :show, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_banheiro
      @banheiro = Banheiro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def banheiro_params
      params.require(:banheiro).permit(:item, :comprado)
    end
end

app/helpers/banheiros_helper.rb
module BanheirosHelper
end

app/views/banheiros/_banheiro.html.erb
<div id="<%= dom_id banheiro %>">

  <p>
    <strong>Item:</strong>
    <%= banheiro.item %>
  </p>

  <p>
    <strong>Comprado:</strong>
    <%= banheiro.comprado %>
  </p>

</div>

app/views/banheiros/_form.html.erb
<%= form_with(model: banheiro) do |form| %>
  <% if banheiro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(banheiro.errors.count, "error") %> prohibited this banheiro from being saved:</h2>

      <ul>
        <% banheiro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :item, style: "display: block" %>
    <%= form.text_field :item %>
  </div>

  <div>
    <%= form.label :comprado, style: "display: block" %>
    <%= form.check_box :comprado %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/banheiros/edit.html.erb
# <h1>Editing banheiro</h1>

# <%= render "form", banheiro: @banheiro %>

# <br>

# <div>
#   <%= link_to "Show this banheiro", @banheiro %> |
#   <%= link_to "Back to banheiros", banheiros_path %>
# </div>

app/views/banheiros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Banheiro</h1>

<div id="banheiros">
  <% @banheiros.each do |banheiro| %>
    <%= render banheiro %>

  <% end %>
</div>

<%= link_to "Novo item", new_banheiro_path %>

app/views/banheiros/new.html.erb
<h1>New banheiro</h1>

<%= render "form", banheiro: @banheiro %>

<br>

<div>
  <button type="button" onclick="window.location.href='<%= root_path %>'">
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAxklEQVRIS2NkoDFgpLH5DHS3wAHoo/lArECmzx4A9SUC8QGYfnQfgBTIk2k4TNsHIEMQlwX/oRLkBh2GfnSDhr8FC4BBmIAnjggGEaH4BRlwAYgdgRgUmeiAKhaADAUZDrIEZBkyIGgBTAEhn8DkQWkeFGwwMPAWEHI5zIUfgQodyAkiYiy4CDWcrEgmlNFA4Z2AxxVEx8FoUQEPAVoU1w+BcaQAiyd0C0BJDxSR5NYJIMNBieAALgsIJVOS5clNLURbRHMLAJ8WMhnOi1xiAAAAAElFTkSuQmCC"/>
  </button>
</div>

app/views/banheiros/show.html.erb
# <p style="color: green"><%= notice %></p>

# <%= render @banheiro %>

# <div>
#   <%= link_to "Edit this banheiro", edit_banheiro_path(@banheiro) %> |
#   <%= link_to "Back to banheiros", banheiros_path %>

#   <%= button_to "Destroy this banheiro", @banheiro, method: :delete %>
# </div>